theme = "semi-native"
icons = "awesome6"
scrolling = "natural"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid}"
interval = 10

[[block]]
block = "bluetooth"
mac = "AC:1D:06:9C:0F:FC"
format = ""

[[block]]
block = "sound"
format = "{volume}"

[[block]]
block = "backlight"
invert_icons = true

[[block]]
block = "battery"
interval = 10 
format = "{percentage} {power}"
full_format = "{percentage}"

[[block]]
block = "time"
interval = 10
format = "%a %d/%m %R"
